version: '3'
services:
  
  #PHP Service
  app:
    command: "composer install"
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/vendor/
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:1.23.1
    hostname: webserver
    container_name: webserver
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./docker-compose/nginx/log:/var/log/nginx
    stdin_open: true
    tty: true
    networks:
      - app-network

  #MySQL Service
  mysql:
    image: mysql:5.7.22
    hostname: mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      # - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
